FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 9005
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["Client.WebApi/Client.WebApi.csproj", "Client.WebApi/"]
RUN dotnet restore "Client.WebApi/Client.WebApi.csproj"
COPY . .
WORKDIR "/src/Client.WebApi"
RUN dotnet build "Client.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Client.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Client.WebApi.dll"]